export const navigation = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about-us' },
  { label: 'Products', href: '/products-and-materials' },
  { label: 'Services', href: '/services' },
  { label: 'Portfolio', href: '/portfolio' },
  { label: 'FAQs', href: '/faqs' },
  { label: 'Contact', href: '/contact-us' },
  { label: 'Appointment', href: '/request-appointment' },
];

export const faqContent = {
  title: 'Frequently Asked Questions',
  description: 'Answers to common questions about veneers, crowns, bridges, and working with Dental Atelier.',
  heroImage: '/images/about-dental-lab-photo-04.webp',
  heroAlt: 'Dental Atelier laboratory workspace',
  intro: 'Here are a few common questions about dental restorations. Please contact us for information specific to your case.',
  sections: [
    { title: 'What is a porcelain veneer or lumineer?', body: 'A porcelain veneer is a thin ceramic shell bonded to the front surface of a tooth. Whether it is suitable depends on an individual dental assessment.' },
    { title: 'What is a crown?', body: 'A crown is a restoration that covers and protects a tooth when a filling or veneer is not sufficient.' },
    { title: 'What is a bridge?', body: 'A bridge replaces one or more missing teeth by being supported by adjacent teeth or implants.' },
    { title: 'Do I have to change my dentist?', body: 'No. We collaborate with your current dentist as part of the treatment process.' },
    { title: 'How can I get a price estimate?', body: 'Contact us with details of your case and we can discuss the next steps with you.' },
  ],
};

export const homePageContent = {
  title: 'Dental Atelier | A state-of-the-art laboratory',
  description: 'Patient-centered dental craftsmanship, digital smile design, and restorative solutions in Brussels.',
  heroImage: '/images/hero-sexy-powerful-smile-slide-02.webp',
  heroAlt: 'Woman with a confident smile',
  intro: 'An ideal smile is linked to certain biometrical features. Discover a thoughtful, collaborative approach to dental craftsmanship.',
  sections: [
    { title: 'Hero eyebrow', body: 'A state-of-the-art laboratory' },
    { title: 'Hero heading', body: 'Designed around your smile.' },
    { title: 'Hero panel label', body: 'Dental Atelier' },
    { title: 'Hero panel copy', body: 'Patient, dentist, and technician working together for a natural result.' },
    { title: 'Feature eyebrow', body: 'A smile that feels like you' },
    { title: 'Feature heading', body: 'Explore what is possible' },
    { title: 'Feature introduction', body: 'Learn about our patient-centered approach, services, and digital planning tools.' },
    { title: 'Smile feature 1 title', body: 'Sexy & powerful smile' },
    { title: 'Smile feature 1 description', body: 'Explore the role of smile aesthetics and discover a more confident smile.' },
    { title: 'Smile feature 2 title', body: 'Comfort & Self-confidence' },
    { title: 'Smile feature 2 description', body: 'Learn about restorative options planned around comfort and your individual needs.' },
    { title: 'Smile feature 3 title', body: 'Looking young, feeling healthy' },
    { title: 'Smile feature 3 description', body: 'Understand how modern restorations can address changes in teeth over time.' },
    { title: 'Smile feature 4 title', body: 'Facial analysis and Digital Smile Design' },
    { title: 'Smile feature 4 description', body: 'Visualize a planned smile and collaborate on your treatment plan.' },
    { title: 'Approach heading', body: 'A collaborative approach' },
    { title: 'Approach copy', body: 'From consultation and case planning to custom shading and delivery, we work closely with your dental team.' },
    { title: 'Contact callout heading', body: 'Ready to talk about your smile?' },
    { title: 'Contact callout copy', body: 'Tell us what you are looking for. We’ll help you understand the next steps.' },
  ],
};

export const pages = {
  'about-us': {
    title: 'About Dental Atelier',
    description: 'Learn about Dental Atelier and our patient-centered approach to dental craftsmanship.',
    heroImage: '/images/about-dental-lab-photo-01.webp',
    heroAlt: 'Dental laboratory workstation with a microscope',
    intro: 'Dental Atelier is here to empower you to live a healthy, happy life with peace of mind. We take a customized, patient-centered approach and believe communication is the key to exceptional care.',
    sections: [
      { title: 'Communication is the key', body: 'Collaboration between the patient, dentist, and technician is central to planning work that feels natural and suits each individual.' },
      { title: 'The latest courses', body: 'Our team continues to develop its knowledge of modern dental techniques, materials, and digital workflows.' },
      { title: 'Mission and goal', body: 'We care that everyone receives exceptional service and carefully considered dental solutions.' },
    ],
  },
  'products-and-materials': {
    title: 'Products & Materials',
    description: 'Explore Dental Atelier products, restorative solutions, and carefully selected materials.',
    heroImage: '/images/about-dental-lab-photo-02.webp',
    heroAlt: 'Equipment inside the Dental Atelier laboratory',
    intro: 'From digital planning to handcrafted restorations, every case is approached with attention to fit, function, and aesthetics.',
    sections: [
      { title: 'Facial Analysis and Digital Smile Design', body: 'Digital imaging helps you visualize a proposed result on your portrait photograph and supports collaborative treatment planning.', href: '/facial-analysis-and-digital-smile-design' },
      { title: 'Diagnostic wax up', body: 'Preview a planned smile on a three-dimensional model before moving forward.' },
      { title: 'Provisional Crowns', body: 'Provisional restorations help evaluate appearance and function during treatment.' },
      { title: 'Crowns & Bridges', body: 'Custom restorations are planned around the needs of each case.' },
      { title: 'Implant Solutions', body: 'Implant restorations are designed in collaboration with the treating dental team.' },
      { title: 'Inlays, Onlays & Veneers', body: 'Conservative ceramic options can restore shape and appearance where appropriate.' },
      { title: 'Materials', body: 'Materials are selected from leading manufacturers to support quality and reliable results.' },
    ],
  },
  services: {
    title: 'Services',
    description: 'Discover Dental Atelier services, from case planning and consultation to pickup and delivery.',
    heroImage: '/images/about-dental-lab-photo-03.webp',
    heroAlt: 'Dental Atelier laboratory workspace',
    intro: 'We work closely with patients and dental professionals to support each case from its initial plan through delivery.',
    sections: [
      { title: 'Price estimation', body: 'The price of a dental product depends on the type of work and the materials required. Contact us to discuss your case.' },
      { title: 'Free consultation', body: 'Consultation helps us understand your needs and answer questions before a case begins.' },
      { title: 'Custom colour shading', body: 'Careful shade matching helps restorations blend with a patient’s natural smile.' },
      { title: 'Facial analysis and Digital Smile Design', body: 'Explore a planned smile using digital imaging and collaborative case planning.', href: '/facial-analysis-and-digital-smile-design' },
      { title: 'Pick-up and delivery', body: 'Dental Atelier provides a pickup and delivery service for dental practices.' },
      { title: 'Diagnostic case planning', body: 'We coordinate with the patient and dentist to plan a case before treatment.' },
    ],
  },
  portfolio: {
    title: 'Portfolio',
    description: 'View examples of dental restorations and smile transformations from Dental Atelier.',
    heroImage: '/images/portfolio-smile-after.webp',
    heroAlt: 'Smile after restorative dental treatment',
    intro: 'Explore examples of dental restorations and smile transformations from Dental Atelier. Before-and-after photos are shown with the labels used in the source portfolio.',
    sections: [],
  },

  'sexy-and-powerful-smile': {
    title: 'Sexy & Powerful Smile',
    description: 'Explore how smile design can support confidence and a natural-looking result.',
    heroImage: '/images/hero-sexy-powerful-smile-slide-01.webp',
    heroAlt: 'Portrait of a woman with a natural smile',
    intro: 'An ideal smile is linked to certain biometrical features. Digital planning and a conversation about your goals can help you explore what may suit you.',
    sections: [{ title: 'Ready for your smile check?', body: 'Tell us what you would like to improve and our team will get back to you.', href: '/smile-check-form' }],
  },
  'comfort-and-self-confidence': {
    title: 'Comfort & Self-confidence',
    description: 'Learn about restorative options designed around comfort, function, and confidence.',
    heroImage: '/images/hero-comfort-self-confidence-slide-01.webp',
    heroAlt: 'Two people smiling together',
    intro: 'Dental concerns can affect how comfortable you feel when smiling. Depending on your needs, ceramic inlays or crowns may be among the options to discuss with your dentist.',
    sections: [{ title: 'Ready for your smile check?', body: 'Share your questions with Dental Atelier and start a conversation about your smile.', href: '/smile-check-form' }],
  },
  'looking-young-feeling-healthy': {
    title: 'Looking Young, Feeling Healthy',
    description: 'Learn how restorative dentistry may help address changes in teeth over time.',
    heroImage: '/images/hero-looking-young-feeling-healthy-slide-01.webp',
    heroAlt: 'Man smiling at his reflection',
    intro: 'Teeth change with age and use. A personalized assessment can help identify restorative options that support healthy function and appearance.',
    sections: [{ title: 'Ready for your smile check?', body: 'Contact us to share your concerns and ask about possible next steps.', href: '/smile-check-form' }],
  },
  'facial-analysis-and-digital-smile-design': {
    title: 'Facial Analysis and Digital Smile Design',
    description: 'Find out how digital imaging can support smile visualization and case planning.',
    heroImage: '/images/hero-smile-check-slide-01.webp',
    heroAlt: 'Two women smiling together',
    intro: 'Digital imaging allows you to see a proposed result on your portrait photograph and helps the patient, dentist, and technician plan together.',
    sections: [{ title: 'Request more information', body: 'Send us a note and our team will be in touch.' }],
  },
};
